import type { OwnerRow, CompanyRow, CompanyDetail } from "./db";

export const MOCK_OWNERS: OwnerRow[] = [
  {
    owner_id: "1",
    owner_name: "Tyler Price",
    company_count: 12,
    avg_ease_score: 72.4,
    avg_contact_frequency_90d: 9.1,
    total_contact_frequency_90d: 109,
    companies_with_spend_data: 10,
  },
  {
    owner_id: "2",
    owner_name: "Sarah Johnson",
    company_count: 9,
    avg_ease_score: 54.8,
    avg_contact_frequency_90d: 5.6,
    total_contact_frequency_90d: 50,
    companies_with_spend_data: 8,
  },
  {
    owner_id: "3",
    owner_name: "Mike Chen",
    company_count: 11,
    avg_ease_score: 38.2,
    avg_contact_frequency_90d: 3.2,
    total_contact_frequency_90d: 35,
    companies_with_spend_data: 7,
  },
  {
    owner_id: "4",
    owner_name: "Emma Davis",
    company_count: 8,
    avg_ease_score: 81.5,
    avg_contact_frequency_90d: 13.4,
    total_contact_frequency_90d: 107,
    companies_with_spend_data: 8,
  },
];

export const MOCK_COMPANIES: CompanyRow[] = [
  // Tyler Price
  {
    hubspot_company_id: "c1",
    company_name: "Acme Marketing Co",
    owner_id: "1",
    owner_name: "Tyler Price",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 18,
    avg_spend_3mo: 2800,
    deal_count_3mo: 3,
    last_engagement_at: daysAgo(1),
    days_since_last_engagement: 1,
    ease_score_0_to_100: 94.2,
  },
  {
    hubspot_company_id: "c2",
    company_name: "Blue Ridge Solutions",
    owner_id: "1",
    owner_name: "Tyler Price",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 11,
    avg_spend_3mo: 5200,
    deal_count_3mo: 2,
    last_engagement_at: daysAgo(4),
    days_since_last_engagement: 4,
    ease_score_0_to_100: 80.7,
  },
  {
    hubspot_company_id: "c3",
    company_name: "Pinnacle Group",
    owner_id: "1",
    owner_name: "Tyler Price",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 7,
    avg_spend_3mo: 1100,
    deal_count_3mo: 1,
    last_engagement_at: daysAgo(9),
    days_since_last_engagement: 9,
    ease_score_0_to_100: 66.3,
  },
  {
    hubspot_company_id: "c4",
    company_name: "Sunbelt Ventures",
    owner_id: "1",
    owner_name: "Tyler Price",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 3,
    avg_spend_3mo: 2400,
    deal_count_3mo: 1,
    last_engagement_at: daysAgo(22),
    days_since_last_engagement: 22,
    ease_score_0_to_100: 41.0,
  },
  {
    hubspot_company_id: "c5",
    company_name: "Horizon Digital",
    owner_id: "1",
    owner_name: "Tyler Price",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 1,
    avg_spend_3mo: 650,
    deal_count_3mo: 1,
    last_engagement_at: daysAgo(61),
    days_since_last_engagement: 61,
    ease_score_0_to_100: 10.7,
  },
  {
    hubspot_company_id: "c6",
    company_name: "Redwood Analytics",
    owner_id: "1",
    owner_name: "Tyler Price",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 0,
    avg_spend_3mo: null,
    deal_count_3mo: 0,
    last_engagement_at: null,
    days_since_last_engagement: null,
    ease_score_0_to_100: 0,
  },
  // Sarah Johnson
  {
    hubspot_company_id: "c7",
    company_name: "Coastal Media Group",
    owner_id: "2",
    owner_name: "Sarah Johnson",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 14,
    avg_spend_3mo: 3400,
    deal_count_3mo: 2,
    last_engagement_at: daysAgo(2),
    days_since_last_engagement: 2,
    ease_score_0_to_100: 88.0,
  },
  {
    hubspot_company_id: "c8",
    company_name: "Apex Retail Partners",
    owner_id: "2",
    owner_name: "Sarah Johnson",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 5,
    avg_spend_3mo: 1800,
    deal_count_3mo: 1,
    last_engagement_at: daysAgo(14),
    days_since_last_engagement: 14,
    ease_score_0_to_100: 52.3,
  },
  {
    hubspot_company_id: "c9",
    company_name: "Summit Health Systems",
    owner_id: "2",
    owner_name: "Sarah Johnson",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 2,
    avg_spend_3mo: null,
    deal_count_3mo: 0,
    last_engagement_at: daysAgo(45),
    days_since_last_engagement: 45,
    ease_score_0_to_100: 23.9,
  },
  // Mike Chen
  {
    hubspot_company_id: "c10",
    company_name: "Forge Manufacturing",
    owner_id: "3",
    owner_name: "Mike Chen",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 9,
    avg_spend_3mo: 7800,
    deal_count_3mo: 2,
    last_engagement_at: daysAgo(6),
    days_since_last_engagement: 6,
    ease_score_0_to_100: 73.3,
  },
  {
    hubspot_company_id: "c11",
    company_name: "Delta Logistics",
    owner_id: "3",
    owner_name: "Mike Chen",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 4,
    avg_spend_3mo: 1500,
    deal_count_3mo: 1,
    last_engagement_at: daysAgo(31),
    days_since_last_engagement: 31,
    ease_score_0_to_100: 33.7,
  },
  {
    hubspot_company_id: "c12",
    company_name: "Northstar Consulting",
    owner_id: "3",
    owner_name: "Mike Chen",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 0,
    avg_spend_3mo: null,
    deal_count_3mo: 0,
    last_engagement_at: daysAgo(88),
    days_since_last_engagement: 88,
    ease_score_0_to_100: 2.2,
  },
  // Emma Davis
  {
    hubspot_company_id: "c13",
    company_name: "Brightpath Education",
    owner_id: "4",
    owner_name: "Emma Davis",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 22,
    avg_spend_3mo: 5600,
    deal_count_3mo: 3,
    last_engagement_at: daysAgo(0),
    days_since_last_engagement: 0,
    ease_score_0_to_100: 100,
  },
  {
    hubspot_company_id: "c14",
    company_name: "Clearview Financial",
    owner_id: "4",
    owner_name: "Emma Davis",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 16,
    avg_spend_3mo: 12500,
    deal_count_3mo: 2,
    last_engagement_at: daysAgo(3),
    days_since_last_engagement: 3,
    ease_score_0_to_100: 89.3,
  },
  {
    hubspot_company_id: "c15",
    company_name: "Vantage Properties",
    owner_id: "4",
    owner_name: "Emma Davis",
    account_status: "Active",
    credits_package: null,
    contact_frequency_90d: 8,
    avg_spend_3mo: 2100,
    deal_count_3mo: 1,
    last_engagement_at: daysAgo(10),
    days_since_last_engagement: 10,
    ease_score_0_to_100: 62.7,
  },
];

export const MOCK_COMPANY_DETAILS: Record<string, CompanyDetail> = {
  c1: {
    metrics: MOCK_COMPANIES[0],
    engagementTypes: [
      { engagement_type: "EMAIL", count: 10 },
      { engagement_type: "CALL", count: 5 },
      { engagement_type: "MEETING", count: 3 },
    ],
    recentEngagements: [
      { engagement_type: "EMAIL", occurred_at: daysAgo(1) },
      { engagement_type: "CALL", occurred_at: daysAgo(3) },
      { engagement_type: "EMAIL", occurred_at: daysAgo(5) },
      { engagement_type: "MEETING", occurred_at: daysAgo(8) },
      { engagement_type: "EMAIL", occurred_at: daysAgo(12) },
    ],
    latestDeal: { amount: 2800, closedate: daysAgo(14) },
  },
  c10: {
    metrics: MOCK_COMPANIES[9],
    engagementTypes: [
      { engagement_type: "CALL", count: 6 },
      { engagement_type: "EMAIL", count: 2 },
      { engagement_type: "MEETING", count: 1 },
    ],
    recentEngagements: [
      { engagement_type: "CALL", occurred_at: daysAgo(6) },
      { engagement_type: "EMAIL", occurred_at: daysAgo(11) },
      { engagement_type: "CALL", occurred_at: daysAgo(18) },
    ],
    latestDeal: { amount: 7800, closedate: daysAgo(22) },
  },
  c13: {
    metrics: MOCK_COMPANIES[12],
    engagementTypes: [
      { engagement_type: "EMAIL", count: 12 },
      { engagement_type: "MEETING", count: 6 },
      { engagement_type: "CALL", count: 3 },
      { engagement_type: "NOTE", count: 1 },
    ],
    recentEngagements: [
      { engagement_type: "EMAIL", occurred_at: daysAgo(0) },
      { engagement_type: "MEETING", occurred_at: daysAgo(2) },
      { engagement_type: "EMAIL", occurred_at: daysAgo(4) },
      { engagement_type: "CALL", occurred_at: daysAgo(7) },
      { engagement_type: "EMAIL", occurred_at: daysAgo(9) },
    ],
    latestDeal: { amount: 5600, closedate: daysAgo(10) },
  },
};

export function getMockDetail(id: string): CompanyDetail {
  if (MOCK_COMPANY_DETAILS[id]) return MOCK_COMPANY_DETAILS[id];

  const metrics = MOCK_COMPANIES.find((c) => c.hubspot_company_id === id);
  if (!metrics) {
    return { metrics: null, engagementTypes: [], recentEngagements: [], latestDeal: null };
  }
  return {
    metrics,
    engagementTypes: [
      { engagement_type: "EMAIL", count: Math.max(1, Math.floor(metrics.contact_frequency_90d * 0.6)) },
      { engagement_type: "CALL", count: Math.max(0, Math.floor(metrics.contact_frequency_90d * 0.3)) },
      { engagement_type: "MEETING", count: Math.max(0, Math.floor(metrics.contact_frequency_90d * 0.1)) },
    ].filter((e) => e.count > 0),
    recentEngagements: metrics.last_engagement_at
      ? [
          { engagement_type: "EMAIL", occurred_at: metrics.last_engagement_at },
          { engagement_type: "CALL", occurred_at: daysAgo((metrics.days_since_last_engagement ?? 0) + 7) },
        ]
      : [],
    latestDeal: metrics.avg_spend_3mo
      ? { amount: metrics.avg_spend_3mo, closedate: daysAgo(30) }
      : null,
  };
}

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString();
}
